server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost/documentation?useSSL=false
    username: root
    password: password
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5
  data:
    rest:
      base-path: /api
  