server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost/LiveDocs?useSSL=false
    username: root
    password: password
    validation-query: SELECT 1
    test-on-borrow: true
    driverClassName: com.mysql.jdbc.Driver
    
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL5
      
  data:
    rest:
      base-path: /api