server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost/docsman?useSSL=false
    username: root
    password: password
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5
