spring:
  main:
    banner-mode: "off"
  datasource:
    url:  jdbc:mysql://localhost/polymer?useSSL=false
    username: root
    password: password
    validation-query: SELECT 1
    test-on-borrow: true
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    show_sql: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5
    properties:
      hibernate:
        cache:
          use_second_level_cache: false
          use_query_cache: false
        generate_statistics: false
logging:
  level:
    org.springframework: false
    org.hibernate: ERROR
  path: logs/dev/
