spring:
  data:
    rest:
      base-path: /api/
  jackson:
    default-property-inclusion: non-null
  mail:
    host: smp.gmail.com
    username: xxxx@gmail.com
    password: xxxxxx
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false